[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/tag_path/*"
  to = "https://cXXXX.csd.dotomi.com"
  status = 200
  force = true
  query = {path = ":path"}
  headers = {X-From = "Netlify", X-Forwarded-Request-Path = "/tag_path", RP-Host = "netlify.cnvrm.com"}
